# travis-ci integration for the kiibohd controller firmware
# XXX Using Ubuntu 14.04 Trusty in root mode (we need universe repo, means we can't use container infra yet)
# Jacob Alexander 2016-2020
# XXX (HaaTa): Travis-CI is being deprecated in favour of GitHub Actions
#              This script is being kept around until the tagged deploy has be ported

sudo: required
dist: xenial

language:
  - c

os:
  - linux

compiler:
  - gcc

# Build Scripts
env:
  # Keyboard Tests
  - DIR=Keyboards SCRIPT=ic_keyboards.bash # Input Club Keyboards
  - DIR=Keyboards SCRIPT=ic_keyboards.bash EnableHostOnlyBuild=true HostTest=kll.py # Input Club Keyboards - Host-Side Build

  # Bootloader Build Tests
  - DIR=Bootloader/Builds SCRIPT=all.bash

  # Deployment Build
  - DIR=Lib/CMake SCRIPT=travis_deploy.bash DEPLOY_NAME=All

# Package Setup
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install software-properties-common -y; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository universe -y; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository ppa:team-gcc-arm-embedded/ppa -y; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install dfu-util tree exuberant-ctags gcc-arm-embedded python3-pip python3-setuptools -y; fi

# System setup
install:
  # Info about OS
  - uname -a

  # Compiler Version
  - ${CC} --version

  # Python Version
  - python --version
  - python3 --version

  # CMake Version
  - cmake --version

  # Prepare pipenv
  - sudo -H pip3 install --upgrade pip
  - sudo -H pip3 install kll

# Run test script(s)
script:
  - cd ${DIR} && PIPENV_ACTIVE=1 COMPILER=${CC} ./${SCRIPT}

# Setup Deploy
before_deploy:
  - mkdir -p deploy

  # Copy files for deployment and prepend the tag name
  - if [[ "$SCRIPT" == "ic_keyboards.bash" ]]; then for f in Keyboards/firmware/*.dfu.bin; do cp -f ${f} deploy/${TRAVIS_TAG}.$(basename ${f}); done; fi
  - if [[ "$SCRIPT" == "all.bash" ]]; then for f in Bootloader/Builds/bootloader/*.bootloader.bin; do cp -f ${f} deploy/${TRAVIS_TAG}.$(basename ${f}); done; fi

  # Show files being deployed
  - tree deploy

# Deploy release
deploy:
  name: ${TRAVIS_TAG}
  body: $(git for-each-ref --format '%(refname) %09 %(taggerdate) %(subject) %(taggeremail)' refs/tags/${TRAVIS_TAG})
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  skip_cleanup: true
  draft: true # XXX Must "publish" on github
  prerelease: true # XXX Set this to false to enable a stable release
  file_glob: true
  file: deploy/*.bin
  on:
    tags: true
    repo: kiibohd/controller
    condition: $TRAVIS_OS_NAME = linux
    condition: $DEPLOY_NAME != ""

