# appveyor file for kiibohd/controller
# Used to test out the Cygwin builds

platform:
  - x64

environment:
  global:
    CYG_MIRROR: http://cygwin.uib.no
    CYG_CACHE: C:/cygwin/var/cache/setup
    CYG_ARCH: x86
    CYG_ROOT: C:/cygwin
    WIN_CMAKE: "/cygdrive/c/Program Files (x86)/CMake/bin"
  matrix:
    # Input Club Keyboard Tests
    - SCRIPT_DIR: Keyboards
      SCRIPT: infinity.bash
    - SCRIPT_DIR: Keyboards
      SCRIPT: infinity_led.bash
    - SCRIPT_DIR: Keyboards
      SCRIPT: ergodox.bash
    - SCRIPT_DIR: Keyboards
      SCRIPT: whitefox.bash

    # Debug Build Tests
    - SCRIPT_DIR: Keyboards/Testing
      SCRIPT: uartout.bash
    - SCRIPT_DIR: Keyboards/Testing
      SCRIPT: usbmuxuart.bash

    # Bootloader Build Tests
    - SCRIPT_DIR: Bootloader/Builds
      SCRIPT: mk20dx128vlf5.bash
    - SCRIPT_DIR: Bootloader/Builds
      SCRIPT: mk20dx256vlh7.bash

init:
  - git config --global core.autocrlf input

install:
  - 'appveyor DownloadFile http://cygwin.com/setup-%CYG_ARCH%.exe -FileName setup.exe'
  - 'setup.exe -qnNdO -R "%CYG_ROOT%" -s "%CYG_MIRROR%" -l "%CYG_CACHE%" -P git -P make -P python3 -P ctags -P tree -P p7zip'
  - '%CYG_ROOT%/bin/bash -lc "cygcheck -dc cygwin"'
  - '%CYG_ROOT%/bin/bash -lc "cd \"$OLDPWD\"/%SCRIPT_DIR% && export wincmake_path=\"%WIN_CMAKE%\" && which cmake"'
  - 'appveyor DownloadFile https://launchpad.net/gcc-arm-embedded/5.0/5-2016-q2-update/+download/gcc-arm-none-eabi-5_4-2016q2-20160622-win32.zip -FileName gcc-arm-none-eabi.zip'
  - dir
  - cmake --version

build_script:
  - '%CYG_ROOT%/bin/bash -lc "cd \"$OLDPWD\" && 7z x -o/ gcc-arm-none-eabi.zip"'
  - '%CYG_ROOT%/bin/bash -lc "cd \"$OLDPWD\" && pwd"'
  - '%CYG_ROOT%/bin/bash -lc "cd \"$OLDPWD\" && tree"'
  - '%CYG_ROOT%/bin/bash -lc "cd \"$OLDPWD\" && cmake --version"'
  - '%CYG_ROOT%/bin/bash -lc "cd \"$OLDPWD\"/%SCRIPT_DIR% && export wincmake_path=\"%WIN_CMAKE%\" && export PATH=\"${wincmake_path}\":$PATH && cmake --version"'
  - '%CYG_ROOT%/bin/bash -lc "cd \"$OLDPWD\" && git --version"'
  - '%CYG_ROOT%/bin/bash -lc "cd \"$OLDPWD\" && python3 --version"'
  - '%CYG_ROOT%/bin/bash -lc "cd \"$OLDPWD\" && arm-none-eabi-gcc --version"'
  - '%CYG_ROOT%/bin/bash -lc "cd \"$OLDPWD\"/%SCRIPT_DIR% && export wincmake_path=\"%WIN_CMAKE%\" && COMPILER=gcc ./%SCRIPT%"'

