name: Linux Build Environment

on: [push, pull_request]

env:
  PIPENV_ACTIVE: 1

jobs:
  firmware:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository universe -y
        sudo add-apt-repository ppa:team-gcc-arm-embedded/ppa -y
        sudo apt-get update
        sudo apt-get install dfu-util tree exuberant-ctags gcc-arm-embedded ninja-build python3-setuptools
    - name: Install kll compiler
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install kll
    - name: Build
      working-directory: Keyboards
      run: ./ic_keyboards.bash

  firmware-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository universe -y
        sudo add-apt-repository ppa:team-gcc-arm-embedded/ppa -y
        sudo apt-get update
        sudo apt-get install dfu-util tree exuberant-ctags gcc-arm-embedded ninja-build python3-setuptools
    - name: Install kll compiler
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install kll
    - name: Test
      working-directory: Keyboards
      run: EnableHostOnlyBuild=true HostTest=kll.py ./ic_keyboards.bash

  other-firmware:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository universe -y
        sudo add-apt-repository ppa:team-gcc-arm-embedded/ppa -y
        sudo apt-get update
        sudo apt-get install dfu-util tree exuberant-ctags gcc-arm-embedded ninja-build python3-setuptools
    - name: Install kll compiler
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install kll
    - name: Build
      working-directory: Keyboards/Others
      run: ./others.bash

  test-builds:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository universe -y
        sudo add-apt-repository ppa:team-gcc-arm-embedded/ppa -y
        sudo apt-get update
        sudo apt-get install dfu-util tree exuberant-ctags gcc-arm-embedded ninja-build python3-setuptools
    - name: Install kll compiler
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install kll
    - name: Build
      working-directory: Keyboards/Testing
      run: ./all_tests.bash

  bootloaders:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository universe -y
        sudo add-apt-repository ppa:team-gcc-arm-embedded/ppa -y
        sudo apt-get update
        sudo apt-get install dfu-util tree exuberant-ctags gcc-arm-embedded ninja-build python3-setuptools
    - name: Install kll compiler
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install kll
    - name: Build
      working-directory: Bootloader/Builds
      run: ./all.bash
